# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class legacy_reads_conversion(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def run_legacy_reads_conversion(self, input_params, context=None):
        """
        :param input_params: instance of type "legacyReadsConversionParams"
           (This module has methods to convert legacy KBaseAssembly types to
           KBaseFile types. 1. KBaseAssembly.SingleEndLibrary to
           KBaseFile.SingleEndLibrary 2. KBaseAssembly.PairedEndLibrary to
           KBaseFile.PairedEndLibrary workspace_name    - the name of the
           workspace for input/output read_library_name - the name of the
           KBaseAssembly.SingleEndLibrary or KBaseAssembly.PairedEndLibrary)
           -> structure: parameter "workspace_name" of String, parameter
           "read_library_name" of String
        :returns: instance of type "ConversionReport" -> structure: parameter
           "report_name" of String, parameter "report_ref" of String
        """
        return self._client.call_method(
            'legacy_reads_conversion.run_legacy_reads_conversion',
            [input_params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('legacy_reads_conversion.status',
                                        [], self._service_ver, context)
